[package]
name = "eaf-rs"
version = "0.4.1"
authors = ["Jens Larsson <jens.dev@fastmail.com>"]
description = "Read/write ELAN files"
repository = "https://github.com/jenslar/eaf-rs"
keywords = ["elan", "eaf", "pfsx", "annotation", "xml"]
edition = "2021"

[dependencies]
time = { version = "0.3.23", features = [ "formatting", "serde" ] }
serde = { version = "1.0.174", features = [ "derive" ] }
quick-xml = { version = "0.29", features = [ "serialize", "overlapped-lists" ] }
serde_json = "1.0.96"
regex = "1.9.1"
rayon = "1.7"
