[package]
name = "eaf-rs"
version = "0.3.0"
authors = ["jens"]
edition = "2018"

[dependencies]
time = { version = "0.3.20", features = [ "formatting", "serde" ] }
serde = { version = "1.0.156", features = [ "derive" ] }
quick-xml = { version = "0.28", features = [ "serialize", "overlapped-lists" ] }
serde_json = "1.0.94"
regex = "1.7.1"
rayon = "1.7"
