[package]
name = "eaf-rs"
version = "0.4.0"
authors = ["jens"]
edition = "2018"

[dependencies]
time = { version = "0.3.21", features = [ "formatting", "serde" ] }
serde = { version = "1.0.163", features = [ "derive" ] }
quick-xml = { version = "0.28.2", features = [ "serialize", "overlapped-lists" ] }
serde_json = "1.0.96"
regex = "1.8.4"
rayon = "1.7"
